"""add_skill_progress_table

Revision ID: 4747e7d87b37
Revises: d8d59952058c
Create Date: 2026-03-12 19:11:54.734078

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4747e7d87b37"
down_revision: str | None = "d8d59952058c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skill_progress",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("roadmap_slug", sa.String(length=100), nullable=False),
        sa.Column("node_id", sa.String(length=255), nullable=False),
        sa.Column("level", sa.String(length=20), server_default="none", nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "roadmap_slug", "node_id", name="uq_skill_progress"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skill_progress")
    # ### end Alembic commands ###
