"""add_is_archived_to_projects_and_issues

Revision ID: 4ff51f09de7e
Revises: 18446590a15c
Create Date: 2026-03-12 16:21:31.750522

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ff51f09de7e"
down_revision: str | None = "18446590a15c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("issues", sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False))
    op.add_column("projects", sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "is_archived")
    op.drop_column("issues", "is_archived")
    # ### end Alembic commands ###
