"""add_parent_id_to_issues

Revision ID: cc481e4ad735
Revises: fb6b2a3dbce3
Create Date: 2026-03-12 14:57:57.988916

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc481e4ad735"
down_revision: str | None = "fb6b2a3dbce3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("issues", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "issues", "issues", ["parent_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "issues", type_="foreignkey")
    op.drop_column("issues", "parent_id")
    # ### end Alembic commands ###
