"""add_is_archived_to_project_members

Revision ID: d8d59952058c
Revises: fad221590bbd
Create Date: 2026-03-13 01:48:12.121584

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8d59952058c"
down_revision: str | None = "fad221590bbd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_members", sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_members", "is_archived")
    # ### end Alembic commands ###
