"""add_is_archived_to_users

Revision ID: fad221590bbd
Revises: 4ff51f09de7e
Create Date: 2026-03-13 01:32:02.489593

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fad221590bbd"
down_revision: str | None = "4ff51f09de7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_archived")
    # ### end Alembic commands ###
